### ISSUE TITLE
What is the license of this repository?

### ISSUE THREAD

**Issue by TatsuyaNakamori** [indiscripts/extendscript#5]
I would like to take advantage of [scriptui/RightClickMenu/RightClickMenu.jsx](https://github.com/indiscripts/extendscript/blob/6643eceaa8a0bec951389ec25ba1c10d697a4125/scriptui/RightClickMenu/RightClickMenu.jsx) code in Adobe ExtendScript.
Are there any conditions of use?
If possible, it would be helpful if you could indicate LICENSE.

Thank you very much.

**Comment by indiscripts** [comment]
Hi @TatsuyaNakamori 

Thanks for your message. All scripts in the [extendscript](https://github.com/indiscripts/extendscript) repo are free to use for whatever purpose. (These are just old snippets that I shared with the community while experimenting.)

Best,
Marc

**Comment by TatsuyaNakamori** [comment]
Thank you so much!
